# Authors: Emily Liang 79453973, Angie Xetey 44067973
# Purpose: Creates a user interface for users to submit requirements for the app & receive the generated code and tests

import gradio as gr 
import subprocess 
import sys 
import os 
import traceback
import json

class UI:
    def __init__(self, results):
        """
        Store results from running the workflow.
        """
        self.parsed_reqs = results["parsed_requirements"]
        self.generated_code = results["generated_code"]
        self.generated_tests = results["generated_tests"]
        self.test_summary = results["test_summary"]
        self.test_output= results["test_output"]
        self.usage_report = results["usage_report"]
    
    def launch_ui(self) -> None:
        """
        Method to launch the UI for user interaction.
        """
        def show_results():
            # Return stored results formatted for display
            return (
                json.dumps(self.parsed_reqs, indent=4),
                self.generated_code,
                self.generated_tests,
                self.test_summary,
                self.test_output,
                json.dumps(self.usage_report, indent=4)
            )
       
        # used a Gradio interface (simpler to implement)
        with gr.Blocks(title="Cyber Defender") as demo:

            gr.Markdown(
                """
				# Cyber Defender
				### Automated Secure Code Generator, Tester & Tracking Suite

				CyberDefender is an intelligent security software assistant that:

				- **Monitors network traffic & system logs**  
				- **Uses AI to detect cyber threats in real time**  
				- **Identifies breaches, malware, & suspicious activity**  
				- **Takes immediate defensive actions**  
				- **Includes password management & encryption features**  
				- Auto-generates secure code and 10+ test cases  
				- Tracks model usage for transparency  

				Provide your system requirements in the first tab to begin the CyberDefender workflow.
   				"""
            )    

            with gr.Tabs():

                # TAB 1 - REQUIREMENTS INPUT 
                with gr.Tab("Requirements"):
                    gr.Markdown("### Enter functional requirements:")
                    requirements_box = gr.Textbox(
                            lines=10,
                            label="Requirements",
                            placeholder="Describe the system you want to build..."
                        )
                    run_button = gr.Button(" Run Cyber Defender")

                # TAB 2 - PARSING REQUIREMENTS
                with gr.Tab("Parsed Output"):
                    gr.Markdown("### Structured Requirements")
                    out_structured = gr.Code()

                # TAB 3 - GENERATED CODE
                with gr.Tab("Generated Code"):
                    gr.Markdown("### Code Generated by Agent")
                    out_code = gr.Code()

                # TAB 4 - GENERATED TESTS
                with gr.Tab("Generated Tests"):
                    gr.Markdown("### Auto-Generated Test Cases")
                    out_tests = gr.Code()

                # TAB 5 - TEST RESULTS
                with gr.Tab("Test Results"):
                    out_summary = gr.Markdown("")
                    out_results = gr.Textbox(label="Full Test Output", lines=15)

                # TAB 6 - TRACKING REPORT 
                with gr.Tab("Tracking Report"):
                    gr.Markdown("### Usage Report")
                    out_tracking = gr.Code()
                    
            run_button.click(
                show_results,
                inputs=[],
                outputs=[out_structured, out_code, out_tests, out_summary, out_results, out_tracking]
            )

        demo.launch()