# Authors: Emily Liang 79453973, Angie Xetey 44067973,Kaomi Booker 85786904
# Purpose: Creates a user interface for users to submit requirements for the app & receive the generated code and tests

import gradio as gr 
import json
from typing import Callable

class UI:
    def __init__(
        self,
        workflow_runner: Callable,
        input_agent,
        code_agent,
        test_agent,
        tracking_agent,
        default_requirements: str
    ):
        """
        Store workflow dependencies so we can re-run the pipeline on each button press.
        """
        self.workflow_runner = workflow_runner
        self.input_agent = input_agent
        self.code_agent = code_agent
        self.test_agent = test_agent
        self.tracking_agent = tracking_agent
        self.default_requirements = default_requirements.strip()
    
    def _run_workflow_with_requirements(self, requirements_text: str):
        """
        Helper invoked by the UI button click to drive the agents and format the response.
        """
        requirements = requirements_text.strip() or self.default_requirements
        results = self.workflow_runner(
            requirements,
            self.input_agent,
            self.code_agent,
            self.test_agent,
            self.tracking_agent
        )
        return (
            json.dumps(results["parsed_requirements"], indent=4),
            results["generated_code"],
            results["generated_tests"],
            results["test_summary"],
            results["test_output"],
            json.dumps(results["usage_report"], indent=4)
        )
    
    def launch_ui(self) -> None:
        """
        Method to launch the UI for user interaction.
        """
       
        # used a Gradio interface (simpler to implement)
        with gr.Blocks(title="Cyber Defender") as demo:

            gr.Markdown(
                """
				# Cyber Defender
				### Automated Secure Code Generator, Tester & Tracking Suite

				CyberDefender is an intelligent security software assistant that:

				- **Monitors network traffic & system logs**  
				- **Uses AI to detect cyber threats in real time**  
				- **Identifies breaches, malware, & suspicious activity**  
				- **Takes immediate defensive actions**  
				- **Includes password management & encryption features**  
				- Auto-generates secure code and 10+ test cases  
				- Tracks model usage for transparency  

				Provide your system requirements in the first tab to begin the CyberDefender workflow.
   				"""
            )    

            with gr.Tabs():

                # TAB 1 - REQUIREMENTS INPUT 
                with gr.Tab("Requirements"):
                    gr.Markdown("### Enter functional requirements:")
                    requirements_box = gr.Textbox(
                            lines=10,
                            label="Requirements",
                            placeholder="Describe the system you want to build...",
                            value=self.default_requirements
                        )
                    run_button = gr.Button(" Run Cyber Defender")

                # TAB 2 - PARSING REQUIREMENTS
                with gr.Tab("Parsed Output"):
                    gr.Markdown("### Structured Requirements")
                    out_structured = gr.Code()

                # TAB 3 - GENERATED CODE
                with gr.Tab("Generated Code"):
                    gr.Markdown("### Code Generated by Agent")
                    out_code = gr.Code()

                # TAB 4 - GENERATED TESTS
                with gr.Tab("Generated Tests"):
                    gr.Markdown("### Auto-Generated Test Cases")
                    out_tests = gr.Code()

                # TAB 5 - TEST RESULTS
                with gr.Tab("Test Results"):
                    out_summary = gr.Markdown("")
                    out_results = gr.Textbox(label="Full Test Output", lines=15)

                # TAB 6 - TRACKING REPORT 
                with gr.Tab("Tracking Report"):
                    gr.Markdown("### Usage Report")
                    out_tracking = gr.Code()
                    
            run_button.click(
                self._run_workflow_with_requirements,
                inputs=[requirements_box],
                outputs=[out_structured, out_code, out_tests, out_summary, out_results, out_tracking]
            )

        demo.launch()